### ISSUE TITLE
functions eat memory

### ISSUE THREAD

**Issue by STMAndreas** [StevenCyb/SecuredLinkedList#2]
Hi,
I use this functions (push and shift) on an ESP32. 
Do you mean you will ever free the used memory?

I check the free heap before and after shift and there is no difference.
Forthermore, the heap gets smaller and smaller with each push.

In your source code I see you allocate new memory with "new" during push but I cannot see any "delete" with shift.

**Comment by StevenCyb** [comment]
Hey,

thanks for pointing out this problem. You are right, just removing the reference will not free the memory.
After I quick look at the code, on clear or any point where I want to remove data, I should indeed use `delete`.
I wrote the code some time ago, so I will need to check and fix it.

I will let you know as soon as I have fixed it.

**Comment by StevenCyb** [comment]
Okay, I fixed it and added a example on how I tested the fix.

Thanks again for pointing out 👍
