### ISSUE TITLE
SecuredLinkedList.h - #endif in wrong position 

### ISSUE THREAD

**Issue by DaveDuncanson** [StevenCyb/SecuredLinkedList#4]
Hi 
Thanks for the thread safe library, one issue, when I first complied the library via PlatformIO , I kept getting Class T redefinition errors.
The issue is that you have the #endif  in the SecuredLinkedList.h the following at the beginning of the file, prior to the Class definitions,  which will be fine if you only include the header file once.  
But if you include it from multiple CPP files, you will get the redefinition class error. 

#ifndef SecuredLinkedList_h
#define SecuredLinkedList_h
#endif

The fix is just to move the #endif to the end of the file.

Rgs
Dave

**Comment by StevenCyb** [comment]
Hey Dave, 
Thanks for pointing out this issue. I am currently on vacation and will check it out. Also feel free to create a PR.

**Comment by StevenCyb** [comment]
Hey, sorry for the late reply. I have adopted your suggested change. Thanks for the hint :)
